"""Direct authoritative remote preflight payload."""

from __future__ import annotations

import base64
import zlib

_PREFLIGHT_ENCODED = (
    "c%1D#Ym?hXa^Lq?Ao$<|Z7#V|Y$wH-r;=q|tja~_@@}P)+GC-xz;KBZ2=Fk#N_#B+_jLF4yzt;dwp00FRcQ&%qhHh0-P6<HRleO-brbweR^>FP"
    "<TTh7Nwco%?KF^^w#f_lY#(-Yl?n;H@>yQ3>uMXcby4IG0Z$ioUDYr*sil|(wfK80WOEh&=j;EDzyF`Rx3|GEco}>dytsM!HGf>CMIvPozps84"
    "Sze2@iFn%V$Gf|qbmNannH8d*EUp6hmx(n1S3NNgkEAHpgmW6KchexPG9Y0qAE&`aB$=pz>Qa0JdKn1*t3}h+W$?Z##Z_GGM5&<xp_+_`HZL;j"
    "6m{g%Iho9`^(wC0GG@uZJS(OdbX>(BH+j0jb`s-^zFx(<q}jycQ!X2vQ^^@N%nH?Vg$!y^VqB95=yn*%k|tRq)yxYFbtwLsB|>v(DE=|imj=vM"
    "G@B}0hClt~_AU(aH4P3#Aw>}W``f#4Lcl-f%_i`q6Oojgd@HK9S-!lP1c?Ofa#xj7IMPi%5>={wRs-6|(S@&q7YYF&E<_o@@JaB;z>aVs<v`QV"
    "ZHYMFqLM|Sh8r|h6%<MRD41SeR218+sFF+~<XI+ABciZv*4O_UP9{pmX;HP=8fFVvkw+mtIUC`oRh{9MfDyoU)g%S*b-$VhFQ!U&NKBi&5Zs$f"
    "Y7eSfai$<lg6~wnWo(x`BZ&a6x7;9~DExw!C42=RCGIs|oLAuly4T@O)I|64#m&tZ^svXjhtTq1Pyw8>YJjx7luc5mB4XsABYE0PkXUY+J&Gm@"
    "Wt*ZF11ew#r{2}Av$|vJl9x|Ok!QghBU+;Zp+ik0wjk2HTvx!nhZjb-MH5b@L(MVH2#;~akPFyI#8bB$<~tnYR|P+<fDK^wpO&;{1ZMJC?BWtQ"
    "B&Ka$i?WHe;#ic_5;J0#B|AjHLZa|#fFBP!3RLmsBmFM8`CLx&GHLRvbm-H3_$YvCU-wB<smbNcp9E}mHpCcl=_V;3#cASrtIfoxMwA(^qDz3c"
    "AOFZSgTNw^D-I99*9>mkv$P?tw!1<!;v}WCo?k747p~D_l-dEvs;yy-VO?6VJb4y>5YOPolC4lrAM!F|s`?v&XBkx=>Lw*qaACj6ranGWW9G5P"
    "4YbxL%|<wJ2_>NS3iV1ORgD_U>NtF{-8Ii$=q$&5m}lX_M=}jUlovGP2Yf?3W{^R8=z4~zsgqJ-e8UVUDQ#JF1s_BSJHZUN4;_cX!(yNWa1W0m"
    "2;qvr{sVT+l>Wv@%qUzMaSW&d!GKxfOplheB3^4g&LPFuUkJd772f6&wB*rM^%UYV*xz|lNL~?kM8M8Id<`CD*MQ8!WVb8wl=j3NJsx<h@O2B}"
    "NS*&f?UV)hx9<hOtb;w#dI%2$@F9^XoN&`LJGq$8lU+Wu+|OVG&eI|XBIZwDhpqsSEz1yi+xnS&4+N_-@U5bx2w@+xpk|~(X0f%p7~vf3UdA@$"
    "updvX!#&b_nA4C~d%`;CpT(yn#klhxjZm;g--Hj~_Z4(>3%-}rdmEPxzblVHWKM$R(o(wW8bHEDUggEWey861o0WnGQs`~>F@<mxffNdSL9%_w"
    "AKR*xp)W4rRO7iv94p?wYBx&?u&AkN%MyIaaq03Z$@!k24)b)K#cJ-WT*jF|qns_*pqQd7eiXJEisEL3mRnkfrDKoP2v7;2TPp^9s^)O=Z<dW2"
    "=(+YoPDD_Z>-@17^qt4ee2>8H|Bz>YSV231YHQjva!9XK+=Tv`hWas9N2}BjSFhYjUO<S!pz`r10w!6NkF`1nDHJ-kLMTAp{xD&!Qsa6Qs9BnV"
    "0r>rRPeI~{@3X=jUVBfLj=G|H)Ns-fs2z;X$J3{Z#xooK*bC^|RI(vgK+qhD@So{is%|A$-P#!p1e)<2&A<1o;W#IHo*y3Q);@&K;IBh0YpuV7"
    "*rUT9anygY*C5cOYWHr05G%P^+igZqd~2h_MZ3k7eeG=Utdy~e&_Hip3w_G&&-eIom|FnuR#n6RpO+iCgm&Z{=MEV)Xh-s}`-nM%Zo_I;ZIhh5"
    "u>u`Cj`|GCwyR)pe##dfXT&#f8sdm)8(Tk`_S{=RW=i$)BC0PaCymPsB@L3RE6#Fl61gez2aXfhnEUygNKryM=7u;D4N~$TinGJ>q<oHGo*GuF"
    "sFdi#Mrc5oCnN5m(?=M5#iY<=OD%?E098l86o_{as)(zppDkj_t7PqVCnF0Ai~~pp<7c@<&j8;A1Xf8?)p8kyQ<VJz;|Nj87Gq<X<~ff{ilX`m"
    "aZ0)T6FO%_rTB!AVi4Uu?-X~_;J=VcdOq{uF)jmMT1&rK%LX(_FU?u&=Nd(7`ju!SScWWAIY-<kGetvLA7^rty!__d=r>=W8Ar+{mp0poPg(wm"
    "nZb!6*=$Aq0B06;cAfG8Y>c0MxCSpP>Rp|~@kwz7#(PK(YJ)HA(s{^2{Vh;I?C|-|%vH46Ny;_-ejfb&Jox*0@b~ke<yJMs>s%C>qQi>;^yx6_"
    "#2)H+5z9KIZ?#B(fH-L=>{8_5w~2F-?4rywMo0F_qeBVJ%q5HWYaKWZ_Wyt9O&03dTIl1XJ%U>Cj-U710<-cgG7rPOhU0Ca&VF&`kEdUqL7fxv"
    "Z+MdJMem-YHp@H>I;y3dhgD2C$h+#i=#F>#R=%$HhuXfCzY%&vojx3@1-5V(?A|o5tcf1v<}evK;SWQ*<iH<jaNRSxz8vYFngL&vm#y#@9bt^?"
    "w!-MZ2actvpYoI*!F4|7C0_=USvfbKV52FAfP0H)<-qDdIa9+R<b`k({@Uz<ed?dz_u&IrC2f#ma>S0dT4EM17+(O3z~{#AT{*Jrj@0c&Wk_A<"
    "82`%;|5g>oZ5Yn6{-l8;QOB>q;g{S9%=(lIHL598=XT4TP4Y<ACH&$2ZJ^T_XPO4z$MnpClNg!unUcqJ50%j`B>(V#o-Oel7Ntt8w+iWK1STn`"
    "Ah&tOb$iMYY^V?NFvZ{Qhz5e+FTYfImm?q+5c3>P>IZ@81{*eyqvb7ubr>FJ+ASQ%jlFGC#iq^%p7k*5-0k8bY0GpY>i7vn^iT-WuGb{wz{?w5"
    "IlOm*m`?Q4pY2C7$JJDUw+hNqSPiGMPN*u&8x#N=AT~xCyI#X4kA6YEOOZX8>+)4cVH@=bI_cF@29f5HmwX3{iAOT!Bl0pW+Ke8>C-aCwA}qSQ"
    "oH}E6fwA|9?V67M$}k2r_HYEl8Ubgml*!l2J2Zd+E`~5LCF~(ObXg;&rPLc@dRD#wdjp-ml_TBWINh;w<lY;kJ66t$^akk;<D2?fOG;m4)rVbC"
    "J=@#`CV<GTX&nRFB?uL?3Nw+Ef@Rs@*)e1QVZaAbU}B54DXSTn#=4PMB^K#Xb3NKmlN*eLkV>s^Yk7$co(XH4$1tLk)o^=Zs-Mun`Y4^UK)Cvu"
    "IqQ}E-S=j5n2uKAtVG8TikyKg2PY)}=&Xjba=wegIp)u~9Y5|D*I%y?JARqL_F)-f0wd(RFYLN7Yx3zD=3k?57RZS5A7gc9L=MDah;z=CWCmWL"
    ">mIpFc5Ah;V6b<p>(rGIBiuHUOV!|eN1tQI9xZ&HOjAu2NH1+b#+pawCiN>9M?8zQWNNUAQ1I!UXI{B6bX<cdpYpmYF?J!Dv1CbRZeL$^8rAt1"
    "pf0?N&yHG%K2e^FbGlG+?#NzXqqPy4b_OcO-Tofq&ggOG@gH7sR8kCL;J(iX-j}XR^mtXFCTdXrpRop38%JI4*p;P2u&<_GMCRFLmq#BRj$+<$"
    "pk{O6-ne_I$U{{Ok5BJ9$uM52lUIuR-*|qOVgvR`DvFd4m1b=r@b(Dpq{epWgVjUf07K=<N9>~>I>R-7g{N1dX&?vI1CI6IE}|pW(;Me$tJibJ"
    "&Ak~vs+H$zriSF&*fX_KPjyzs*96_lI%!a0yr3Bv32oHH3@AYzCv}}XbKH%KhQ-6pX0(*MTCb&OxQhFR`c(b4U*k+Qnj<<v1^f7hMAAeG+){l^"
    "&MdyhVsc|oFbj`OSd;qV=8|e%WWQT-+^K>kz}=j`!uH(&Hop{AH?zpTTH4vp0$dna4#kd-o3x(g)tum|zenRomg$M;&gO#zoCgZj3n@Qh>c+oM"
    "BQ0_>T)j@3KiH!|`r)WasIj}C`TC2Va^{5^E%IoTX|BH9jG7uyWoR><E8%^p_*iIpgogTsq3Y1P<0WWC^_Z8(ZRFF-c?-)V=QNg1bH~HgH!A&e"
    "txa`r%wbAgC<^oqD?#U50?uowtJAJErGdjfzrQC5gny+^O=n)|(;_LpFTLudx!1RfmFqiVWucI(03L;UrsTK1`z&l%X%~F5*LWRSVduG`VvxSD"
    "xbYHk;S`n@Y;t_*OkJEF<<pGpGCHuNdgw(*3q_kn!!JTr^#{32QkCC1Nu?PsU;TagMUijwhThX*XK{0ycpu^TU6Mb}d!0qS5poIFmh3Lu65pz8"
    "$&wFYbSF+bBkq}=)hSM8$0ynj_Kfs$3sK>{)N%n|uCp|8KnIr-5%7@j6xQ=%gY~&euvedFzp&+LL2t1!N$J&ebmk7NlXs#~OXUn$ofC-IqO)NI"
    "@|DO9N_<>!7C5>d9JshDp&34|2weqGG6Lrcv0J)fDy0Db+NiARNJzQvSlT@syu+L)zv?frUg6#ndpU{|g{RsQb>bmopgP48XO^=Xfpoxj<$ft#"
    "C5&F|MiM%jq^#Q#&yCx}ywzli3EY=#^%yWm$*#d_wW@7)ZNueiaA-(Bs8TiWB~`6MT$rwCz@<hly0PzSQm<?>n0Cqgs7zF_hNwzpVV6-0wEHTm"
    ";=M^8;=1}MBgKoZkyClz<xBqn<EOQXyrkojnmLmYUNqPyqls&-YEo|OP(z~dubtNpRbUU}Xk+m$1Dl4VD7f$Zvxyc7@HKEa@e8{N_WjN1TUx6B"
    "#p=)ztn<Dc=2_Dw=2Jo})1*jhmZvS_WGUHv>t7*UvplJ8d?%Y8?ibfDJg3F|EENWpOR7~&9tshioxMyyfKg&%14XQ_H3~TM#!Tgz>~UlXIg;Z3"
    "T(%v=WT=LPj9N7rRYrwu<r;AZta;@Y%%s<TLXugl;%L#8<+~qzIXW<};vfF<=0D#49KZhl_U-#OZ{wd{-~EU`OAyh7aQ>9kb1*gYj6lvLe4t4?"
    "(MDf!YLP#<O`=K7S4MzM@>zma%=pv5wWS*b=k%yn*5{05%t$U?wkNPcb>=);jx-Cl&)|8;J!T1Y1&i->FeX_hyP*lT$%pHryPD_=D;yUm4|uqb"
    "(?TR=<d+GnUsk|7Ck4?|*U-g}?sZ`M1IVbA&yo963=ux_TLJJy*SbRr<Ixz|o#>M^RPV#v^%#4{olM!(2}Xcb{jBw#fTVu@hj;&!{)YqDyh>P4"
    "2E&`+#Aakt-u(GpP$cOG34UJ&I8kUHV-~{kUdHN>>%R}JzEFimc%9JS>$19TU_`3EsiYe|@AnvW2Q!GSR+G#8At$VzUx^?ab|m_COKcsd*cm}F"
    "w(~l*F2)_GgaJDRJiMb+7(BcOM+YJEMVB`ubR${6;*+J_@v|!b2B_(RnsA#&m6WqSS2ZiTR^4}|a21Dg@A@SyOH~&j*WY>Jp{1AI&c~$Q4k-rx"
    "{zFd<X16$g_Gh$6?;*IlZNM*(R?O7x>%?_tjt0UqGpZ$4A~g9E&}pRTJ3r3}_Xu+gb0JTu?d;tTM4f-rX5l;8PQ>P`gs##XcE!gC15MrGP33_6"
    "pnZlbO$QZ=+9i?XwdG^)ua5jKkst2(Kr?%z)q%Q5F;5Vtm$swsc7m(!TRKQ<t?U%<ds==BoYr)Q$38?+7!{)uqOzxCLp!`JKa|zS(nK~iUp7f2"
    "x;NbBOlA%cy)`IBgGagxH1n?wJg_#bCJu<n<=CI9qTPDi!b7L9^bqo_k)jrR$KW`(CpdUv1RjHV1UCl`GSo+_yg>czzq#YMY%^%YYdcAQGc@Mv"
    "o9vuC$(^1>PLebGLq1zwnwWwO$3wAfEvdM{Kq*=lEM=4R#yItRKj$4&EY*z20Qc%Zz6YNVdT^^WRF^*PLjYPLn?T+zUiIMf;kS}2zt~(e&N0!J"
    ";2+SONB659AGe}dJ8>dq!S8v*z3N?Yq_Gn!l=0^OBuMG^htV|<>Ib|&X9Z|3vqempR2p{7=#4>$agLV2;5=L!n(sKeM(rF_IP6l~;6bW$M^Mtw"
    "s*ROUI5p%J%8$_ap3C1afHiQRt%>w+9W3qrtmh>!ub;OFNc6FKRP87%t;SE#)am%k=tH;L;0{as3Z?W<K>N^^i7Z^}7%Eq>plU^o`9n^8u}Y|4"
    "5mU#3kY8|=$y!9fV(|cbnelip{_10wB1w<b`o=HpzNL@6Dtq&MV(D07sHEQw)P$r}QDDI_;gLO?Ek0osAu_sE8-BeK>r1-tRQhfDoymb#TcKhv"
    "ea%<*Rg2Eu?=<LDCw7{!oRJFIduHx1c6((n)y=sBvm{m~7*rUE^!5LQb;YaIsyNdS?dqy>?6tnNb5%sSV%IyfbH=)IQ6fngJL+@u3B@@N+IxCU"
    "R{hnnfYK*rrb&xB%7SnGlD-$o_906aBd_;P+|}yO8Hy_=2M4POgI0w9l>VzyLgoybd)yxAHyTw)=((u<mtXR>RK1hapgLr#a^3UjBr?oV$|IyB"
    "p<`9Y6ORH_?(u8mA1_Vue+PhwP}T>F#-l;=N9AGiSz;PLFJ}+!dM#@8tCrt>^UXj1OaEu))DK!>=eMU_O=o-ce%4YEq<fbqf8SEi*(T{Gr}t~|"
    "Cp;sSf#k+(GJ#a;0TI(uPgYF%M`v0rOmatFF-cMbpa#rOtE$uaS7T?4AVN*#XH~<`Ur<3w>huEsn8oMvux%1QL4>1f^Ism${4Il%j!Cf-Zb5Fv"
    "wR|p9tR-3(`QrwoS4>RtT@GHu6k^G14@!tti?oEdlyQCgDQ}{elPf$<kpGBd$|uC6O>xYJJ=U$O{{=Iww#o"
)
PREFLIGHT_SCRIPT = zlib.decompress(base64.b85decode(_PREFLIGHT_ENCODED)).decode("utf-8")
